name: Tests

on:
  pull_request:
  push:
    branches:
      - main
jobs:
  static-and-unit-tests:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Add local bin to PATH
        run: |
          echo "${HOME}/.local/bin" >> $GITHUB_PATH
      - name: Install dependencies
        run: |
          sudo apt install -y python3-pip python3-venv
          python3 -m venv ${HOME}/.venv
          pip install -U pip wheel setuptools
          pip install -U -r requirements.txt -r requirements-dev.txt
      - name: Run black
        run: |
          source ${HOME}/.venv/bin/activate
          make test-black
      - name: Run codespell
        run: |
          source ${HOME}/.venv/bin/activate
          make test-codespell
      - name: Run flake8
        run: |
          source ${HOME}/.venv/bin/activate
          make test-flake8
      - name: Run mypy
        run: |
          source ${HOME}/.venv/bin/activate
          make test-mypy
      - name: Run unit tests
        run: |
          source ${HOME}/.venv/bin/activate
          make test-units
      - name: Install LXD
        run: |
          sudo apt install -y snap
          sudo systemctl start snapd
          sudo snap wait system.seeded
          sudo snap install lxd
      - name: Run integration tests
        run: |
          source ${HOME}/.venv/bin/activate
          make test-integrations
      - name: Upload code coverage
        uses: codecov/codecov-action@v1
